### ISSUE TITLE
Creating default object from empty value

### ISSUE THREAD

**Issue by lawrence615** [destinydriven/cakephp-highcharts-plugin#2]
Hi all,

I have seen this charts used somewhere and i liked them a lot. I would therefore want to implement the same in a web system that am building.

I am however experiencing some problems. This is the error am getting

Warning (2): Creating default object from empty value [APP\Plugin\HighCharts\Controller\Component\HighChartsComponent.php, line 202]
Warning (2): Creating default object from empty value [APP\Plugin\HighCharts\Controller\Component\HighChartsComponent.php, line 252]
Warning (2): Creating default object from empty value [APP\Plugin\HighCharts\Controller\Component\HighChartsComponent.php, line 266]
Warning (2): Creating default object from empty value [APP\Plugin\HighCharts\Controller\Component\HighChartsComponent.php, line 281]
Warning (2): Creating default object from empty value [APP\Plugin\HighCharts\Controller\Component\HighChartsComponent.php, line 351]
Warning (2): Creating default object from empty value [APP\Plugin\HighCharts\Controller\Component\HighChartsComponent.php, line 376]
Warning (2): Creating default object from empty value [APP\Plugin\HighCharts\Controller\Component\HighChartsComponent.php, line 377]
Warning (2): Creating default object from empty value [APP\Plugin\HighCharts\Controller\Component\HighChartsComponent.php, line 380]
Warning (2): Creating default object from empty value [APP\Plugin\HighCharts\Controller\Component\HighChartsComponent.php, line 427]

This errors appear when i call the column action in my controller  as well as when i go directly to HighChartsDemo.

please help.

Thanks in advance

**Comment by flaggalagga** [comment]
This happens to a lot of options, in plotOptionsColumnDataLabelsXXX & plotOptionsSeriesDataLabelsXXX and I have not found another way to sort this out than to change the error reporting.

Example : 'plotOptionsColumnDataLabelsEnabled' => true gives you "Warning (2): Creating default object from empty value "
