### ISSUE TITLE
Chart type columnrange usable?

### ISSUE THREAD

**Issue by ThomsonIT** [destinydriven/cakephp-highcharts-plugin#29]
Hi, i want to use the columnrange chart type. Does this plugin support the type? I can't get it to work.

**Comment by ThomsonIT** [comment]
It was not integrated but i managed to integrate it by myself. I try to create a pull request.

**Comment by destinydriven** [comment]
@ThomsonIT Sorry, I've been AFK all morning. I recognize that this plugin lacks a few features and I do have plans to change the way the entire component works to make things easier. But in the mean time, a pull request would be lovely. :D
